orchestration_microservice:
  database:
    db_username: invinsible
    db_passcode: $omniman#
    db_url: localhost
    db_port: 9001
    db_name: orchestration_bank


access_control_microservice:
  database:
    db_username: invinsible
    db_passcode: $omniman#
    db_url: localhost
    db_port: 9020
    db_name: access_control_bank


hotel_microservice:
  database:
    db_username: invinsible
    db_passcode: $omniman#
    db_url: localhost
    db_port: 9040
    db_name: hotel_bank


analytics_microservice:
  database:
    db_username: invinsible
    db_passcode: $omniman#
    db_url: localhost
    db_port: 9090
    db_name: analytics_bank

  
audit_logging_microservice:
  database:
    db_username: invinsible
    db_passcode: $omniman#
    db_url: localhost
    db_port: 9095
    db_name: audit_logging_bank

  
auth_microservice:
  database:
    db_username: invinsible
    db_passcode: $omniman#
    db_url: localhost
    db_port: 9010
    db_name: auth_bank

  
booking_microservice:
  database:
    db_username: invinsible
    db_passcode: $omniman#
    db_url: localhost
    db_port: 9070
    db_name: booking_bank

  
room_microservice:
  database:
    db_username: invinsible
    db_passcode: $omniman#
    db_url: localhost
    db_port: 9050
    db_name: room_bank

  
payment_gateway_microservice:
  database:
    db_username: invinsible
    db_passcode: $omniman#
    db_url: localhost
    db_port: 9060
    db_name: payment_gateway_bank

  
review_microservice:
  database:
    db_username: invinsible
    db_passcode: $omniman#
    db_url: localhost
    db_port: 9005
    db_name: review_bank
  
  
tenant_microservice:
  database:
    db_username: invinsible
    db_passcode: $omniman#
    db_url: localhost
    db_port: 9030
    db_name: tenant_bank

  
user_microservice:
  database:
    db_username: invinsible
    db_passcode: $omniman#
    db_url: localhost
    db_port: 9080
    db_name: user_bank


  











